### ISSUE TITLE
Launch file does not exist in this repo

### ISSUE THREAD

**Issue by tall1** [tasada038/ros2_robot_react_app#2]
In the README it is mentioned:
```shell
ros2 launch ros2_robot_react_app ping_sonar.launch.py
```

But this launch file does not exist.
Plus, could you verify that this repo works? I'm trying it but with no success.

**Comment by tasada038** [comment]
Thank you for bringing up the issue, @tall1.
There was a typo in the README. The correct command is "ros2 launch rosbridge_server rosbridge_websocket_launch.xml", as the specified file does not exist.

Launching the rosbridge server with this command should resolve the issue.
May I proceed to close this issue?
